language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-ngal' ]; then cd .. && eval "mv $currentfolder generator-ngal" && cd generator-ngal; fi

